version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: "yourpassword123"  # ใส่รหัสผ่านตรงนี้ให้ตรงกับ MYSQL_ROOT_PASSWORD
      DB_DATABASE: numer
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword123  # กำหนดรหัสผ่าน root
      MYSQL_DATABASE: numer
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
